id = "axiom-ic"
name = "Axiom-IC"
version = "0.0.1"
schema_version = 1
authors = ["Axiom-IC Contributors"]
description = "Language support for Axiom-IC bytecode"
repository = "https://github.com/axiom-ic/axiom-ic"

[grammars.axiom_ic]
repository = "file:///Users/danielhamen/Desktop/projects/dev/Axiom-IC/axiom-ic/ext/zed/tree-sitter-axiom-ic"
rev = "1e33d1ad2c87c4d37c4d6d5d8d198c5c4797d27c"
